INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (1, N'Item Selection', N'DIV#Item selection', 1, 1, 1, 1)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (2, N'Time and Cost', N'DIV#Time and Cost', 1, 1, 1, 1)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (3, N'Repairable Cost Trend', N'DIV#Cost Trend', 1, 1, 1, 1)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (4, N'Number of Repairs Per Year', N'DIV#Number of Repairs', 1, 1, 1, 1)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (5, N'Work Orders', N'DIV#Work Orders', 1, 1, 1, 400)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (6, N'Demand Supplier Locations ', N'DIV#Demand/Supplier Locations', 1, 1, 1, 1)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (7, N'Top 5 Suppliers', N'DIV#Top 5 Suppliers', 1, 1, 1, 400)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (8, N'Suppliers and Supplier Performance', N'Suppliers and Suppliers Performance', 1, 1, 1, 1)
INSERT INTO [dbo].[Widget] ([WidgetID], [WidgetName], [HTMLId], [TopX], [TopY], [WWidth], [WHeight]) VALUES (9, N'Failure Causes', N'DIV#Failure Causes', 1, 1, 400, 400)
